packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.21.0
  prettier: ^3.5.2
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.2
  class-variance-authority: ^0.7.1
  tailwind-merge: ^2.6.0

catalogs:
  react-native:
    react-native: ~0.76.7
    react-native-css-interop: ~0.0.36
    react-native-reanimated: ~3.16.6
    nativewind: ~4.0.36
  react18:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
