packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.24.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2
  class-variance-authority: ^0.7.1
  tailwind-merge: ^2.6.0

catalogs:
  react-native:
    react-native: ~0.77.2
    react-native-css-interop: ~0.0.36
    react-native-reanimated: ~3.17.2
    nativewind: ~4.0.36
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.20
    "@types/react-dom": ^18.3.6
