packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.21.0
  prettier: ^3.5.2
  tailwindcss: ^3.4.17
  typescript: ^5.6.3
  zod: ^3.23.8
  class-variance-authority: ^0.7.1
  tailwind-merge: ^2.5.4

catalogs:
  react-native:
    react-native: ~0.78.0
    react-native-css-interop: ~0.0.36
    react-native-reanimated: ~3.16.6
    nativewind: ^4.1.23
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5
