name: 🐞 Bug Report
description: Help us fix problems by reporting them here.
title: "bug: "
labels: ["🐞❔ unconfirmed bug"]
body:
  - type: textarea
    attributes:
      label: Environment Info
      description: |
        Tell us about your setup.

        Run this command in your project folder and paste the result below:
        ```bash
        npx envinfo --system --binaries
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: What went wrong? What did you expect to happen instead?
    validations:
      required: true
  - type: input
    attributes:
      label: Link to Example
      description: |
        Can you share a link to a project that shows the bug? (Very helpful!)
        If you don't, we might not be able to fix it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to Reproduce
      description: How can we make the bug happen ourselves? Tell us the steps. (Code examples are great!)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything Else?
      description: Add any other info that might help, like screenshots.